spring:
  application:
    name: spring-cloud-demo2
  datasource:
    password: 12345678
    username: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
